// IPA pronunciation dictionary for common English words.
// Uses espeak-ng en-us notation: ASCII consonants + IPA vowels/diacritics.
// Lookup is case-insensitive (keys are lowercase).

export const IPA_DICT: Record<string, string> = {
  // Articles / determiners
  "a": "ə",
  "an": "æn",
  "the": "ðə",
  "this": "ðɪs",
  "that": "ðæt",
  "these": "ðiːz",
  "those": "ðoʊz",
  "some": "sʌm",
  "any": "ˈɛni",
  "each": "iːtʃ",
  "every": "ˈɛvri",
  "all": "ɔːl",
  "both": "boʊθ",
  "few": "fjuː",
  "more": "mɔːr",
  "most": "moʊst",
  "other": "ˈʌðər",
  "such": "sʌtʃ",
  "no": "noʊ",
  // Pronouns
  "i": "aɪ",
  "me": "miː",
  "my": "maɪ",
  "myself": "maɪˈsɛlf",
  "we": "wiː",
  "our": "aʊr",
  "ours": "aʊrz",
  "ourselves": "aʊrˈsɛlvz",
  "you": "juː",
  "your": "jɔːr",
  "yours": "jɔːrz",
  "yourself": "jɔːrˈsɛlf",
  "he": "hiː",
  "him": "hɪm",
  "his": "hɪz",
  "himself": "hɪmˈsɛlf",
  "she": "ʃiː",
  "her": "hɜːr",
  "hers": "hɜːrz",
  "herself": "hɜːrˈsɛlf",
  "it": "ɪt",
  "its": "ɪts",
  "itself": "ɪtˈsɛlf",
  "they": "ðeɪ",
  "them": "ðɛm",
  "their": "ðɛr",
  "theirs": "ðɛrz",
  "themselves": "ðɛmˈsɛlvz",
  "who": "huː",
  "whom": "huːm",
  "whose": "huːz",
  "which": "wɪtʃ",
  "what": "wɒt",
  "whatever": "wɒtˈɛvər",
  // Common verbs
  "is": "ɪz",
  "are": "ɑːr",
  "was": "wɒz",
  "were": "wɜːr",
  "be": "biː",
  "been": "bɪn",
  "being": "ˈbiːɪŋ",
  "have": "hæv",
  "has": "hæz",
  "had": "hæd",
  "having": "ˈhævɪŋ",
  "do": "duː",
  "does": "dʌz",
  "did": "dɪd",
  "doing": "ˈduːɪŋ",
  "will": "wɪl",
  "would": "wʊd",
  "shall": "ʃæl",
  "should": "ʃʊd",
  "may": "meɪ",
  "might": "maɪt",
  "must": "mʌst",
  "can": "kæn",
  "could": "kʊd",
  "get": "ɡɛt",
  "gets": "ɡɛts",
  "got": "ɡɒt",
  "gotten": "ˈɡɒtən",
  "go": "ɡoʊ",
  "goes": "ɡoʊz",
  "went": "wɛnt",
  "gone": "ɡɒn",
  "going": "ˈɡoʊɪŋ",
  "come": "kʌm",
  "comes": "kʌmz",
  "came": "keɪm",
  "coming": "ˈkʌmɪŋ",
  "make": "meɪk",
  "makes": "meɪks",
  "made": "meɪd",
  "making": "ˈmeɪkɪŋ",
  "know": "noʊ",
  "knows": "noʊz",
  "knew": "njuː",
  "known": "noʊn",
  "think": "θɪŋk",
  "thinks": "θɪŋks",
  "thought": "θɔːt",
  "thinking": "ˈθɪŋkɪŋ",
  "take": "teɪk",
  "takes": "teɪks",
  "took": "tʊk",
  "taken": "ˈteɪkən",
  "see": "siː",
  "sees": "siːz",
  "saw": "sɔː",
  "seen": "siːn",
  "seeing": "ˈsiːɪŋ",
  "look": "lʊk",
  "looks": "lʊks",
  "looked": "lʊkt",
  "looking": "ˈlʊkɪŋ",
  "want": "wɒnt",
  "wants": "wɒnts",
  "wanted": "ˈwɒntɪd",
  "give": "ɡɪv",
  "gives": "ɡɪvz",
  "gave": "ɡeɪv",
  "given": "ˈɡɪvən",
  "use": "juːz",
  "uses": "ˈjuːzɪz",
  "used": "juːzd",
  "find": "faɪnd",
  "finds": "faɪndz",
  "found": "faʊnd",
  "tell": "tɛl",
  "tells": "tɛlz",
  "told": "toʊld",
  "ask": "ɑːsk",
  "asked": "ɑːskt",
  "seem": "siːm",
  "seems": "siːmz",
  "seemed": "siːmd",
  "feel": "fiːl",
  "feels": "fiːlz",
  "felt": "fɛlt",
  "try": "traɪ",
  "tries": "traɪz",
  "tried": "traɪd",
  "leave": "liːv",
  "leaves": "liːvz",
  "left": "lɛft",
  "call": "kɔːl",
  "calls": "kɔːlz",
  "called": "kɔːld",
  "keep": "kiːp",
  "keeps": "kiːps",
  "kept": "kɛpt",
  "let": "lɛt",
  "begin": "bɪˈɡɪn",
  "began": "bɪˈɡæn",
  "show": "ʃoʊ",
  "shows": "ʃoʊz",
  "showed": "ʃoʊd",
  "hear": "hɪər",
  "heard": "hɜːrd",
  "play": "pleɪ",
  "plays": "pleɪz",
  "played": "pleɪd",
  "run": "rʌn",
  "runs": "rʌnz",
  "ran": "ræn",
  "move": "muːv",
  "moves": "muːvz",
  "moved": "muːvd",
  "live": "lɪv",
  "lives": "lɪvz",
  "lived": "lɪvd",
  "believe": "bɪˈliːv",
  "hold": "hoʊld",
  "bring": "brɪŋ",
  "brought": "brɔːt",
  "write": "raɪt",
  "wrote": "roʊt",
  "written": "ˈrɪtən",
  "read": "riːd",
  "stand": "stænd",
  "stood": "stʊd",
  "speak": "spiːk",
  "spoke": "spoʊk",
  "spend": "spɛnd",
  "spent": "spɛnt",
  "put": "pʊt",
  "set": "sɛt",
  "meet": "miːt",
  "met": "mɛt",
  "pay": "peɪ",
  "paid": "peɪd",
  "sit": "sɪt",
  "sat": "sæt",
  "learn": "lɜːrn",
  "learned": "lɜːrnd",
  "change": "tʃeɪndʒ",
  "lead": "liːd",
  "understand": "ˌʌndərˈstænd",
  "watch": "wɒtʃ",
  "follow": "ˈfɒloʊ",
  "stop": "stɒp",
  "create": "kriˈeɪt",
  "start": "stɑːrt",
  "wait": "weɪt",
  "help": "hɛlp",
  "turn": "tɜːrn",
  "open": "ˈoʊpən",
  "close": "kloʊz",
  "walk": "wɔːk",
  "send": "sɛnd",
  "sent": "sɛnt",
  "build": "bɪld",
  "built": "bɪlt",
  "fall": "fɔːl",
  "fell": "fɛl",
  "fallen": "ˈfɔːlən",
  "grow": "ɡroʊ",
  "grew": "ɡruː",
  "grown": "ɡroʊn",
  "draw": "drɔː",
  "drew": "druː",
  "buy": "baɪ",
  "bought": "bɔːt",
  "lose": "luːz",
  "lost": "lɒst",
  "win": "wɪn",
  "won": "wʌn",
  "eat": "iːt",
  "ate": "eɪt",
  "eaten": "ˈiːtən",
  "sleep": "sliːp",
  "slept": "slɛpt",
  "work": "wɜːrk",
  "works": "wɜːrks",
  "worked": "wɜːrkt",
  "working": "ˈwɜːrkɪŋ",
  "say": "seɪ",
  "says": "sɛz",
  "said": "sɛd",
  "saying": "ˈseɪɪŋ",
  // Common nouns
  "time": "taɪm",
  "year": "jɪər",
  "years": "jɪərz",
  "people": "ˈpiːpl",
  "way": "weɪ",
  "day": "deɪ",
  "days": "deɪz",
  "man": "mæn",
  "men": "mɛn",
  "woman": "ˈwʊmən",
  "women": "ˈwɪmɪn",
  "child": "tʃaɪld",
  "children": "ˈtʃɪldrən",
  "world": "wɜːrld",
  "life": "laɪf",
  "hand": "hænd",
  "part": "pɑːrt",
  "place": "pleɪs",
  "case": "keɪs",
  "week": "wiːk",
  "company": "ˈkʌmpəni",
  "system": "ˈsɪstəm",
  "program": "ˈproʊɡræm",
  "question": "ˈkwɛstʃən",
  "government": "ˈɡʌvərnmənt",
  "number": "ˈnʌmbər",
  "night": "naɪt",
  "point": "pɔɪnt",
  "home": "hoʊm",
  "water": "ˈwɔːtər",
  "room": "ruːm",
  "mother": "ˈmʌðər",
  "area": "ˈɛriə",
  "money": "ˈmʌni",
  "story": "ˈstɔːri",
  "fact": "fækt",
  "month": "mʌnθ",
  "lot": "lɒt",
  "right": "raɪt",
  "study": "ˈstʌdi",
  "book": "bʊk",
  "eye": "aɪ",
  "job": "dʒɒb",
  "word": "wɜːrd",
  "business": "ˈbɪznɪs",
  "issue": "ˈɪʃuː",
  "side": "saɪd",
  "kind": "kaɪnd",
  "head": "hɛd",
  "house": "haʊs",
  "service": "ˈsɜːrvɪs",
  "friend": "frɛnd",
  "father": "ˈfɑːðər",
  "power": "ˈpaʊər",
  "hour": "ˈaʊər",
  "game": "ɡeɪm",
  "line": "laɪn",
  "end": "ɛnd",
  "among": "əˈmʌŋ",
  "form": "fɔːrm",
  "body": "ˈbɒdi",
  "name": "neɪm",
  "car": "kɑːr",
  "city": "ˈsɪti",
  "community": "kəˈmjuːnɪti",
  "family": "ˈfæməli",
  "country": "ˈkʌntri",
  "school": "skuːl",
  "state": "steɪt",
  "group": "ɡruːp",
  "idea": "aɪˈdɪə",
  "information": "ˌɪnfərˈmeɪʃən",
  "back": "bæk",
  "parent": "ˈpɛrənt",
  "face": "feɪs",
  "others": "ˈʌðərz",
  "level": "ˈlɛvəl",
  "office": "ˈɒfɪs",
  "door": "dɔːr",
  "health": "hɛlθ",
  "person": "ˈpɜːrsən",
  "art": "ɑːrt",
  "war": "wɔːr",
  "history": "ˈhɪstəri",
  "party": "ˈpɑːrti",
  "result": "rɪˈzʌlt",
  "morning": "ˈmɔːrnɪŋ",
  "reason": "ˈriːzən",
  "research": "ˈriːsɜːrtʃ",
  "girl": "ɡɜːrl",
  "guy": "ɡaɪ",
  "moment": "ˈmoʊmənt",
  "air": "ɛr",
  "teacher": "ˈtiːtʃər",
  "force": "fɔːrs",
  "education": "ˌɛdʒʊˈkeɪʃən",
  "minute": "ˈmɪnɪt",
  "food": "fuːd",
  "plant": "plænt",
  "animal": "ˈænɪməl",
  "music": "ˈmjuːzɪk",
  "color": "ˈkʌlər",
  "colour": "ˈkʌlər",
  "tree": "triː",
  "dog": "dɒɡ",
  "cat": "kæt",
  "sun": "sʌn",
  "moon": "muːn",
  "star": "stɑːr",
  "sea": "siː",
  "earth": "ɜːrθ",
  "fire": "ˈfaɪər",
  "ground": "ɡraʊnd",
  "road": "roʊd",
  "river": "ˈrɪvər",
  "mountain": "ˈmaʊntɪn",
  "sky": "skaɪ",
  "rain": "reɪn",
  "wind": "wɪnd",
  "snow": "snoʊ",
  "light": "laɪt",
  "sound": "saʊnd",
  "voice": "vɔɪs",
  "heart": "hɑːrt",
  "blood": "blʌd",
  "love": "lʌv",
  "dream": "driːm",
  "truth": "truːθ",
  "language": "ˈlæŋɡwɪdʒ",
  "age": "eɪdʒ",
  "space": "speɪs",
  "technology": "tɛkˈnɒlədʒi",
  "phone": "foʊn",
  "computer": "kəmˈpjuːtər",
  "internet": "ˈɪntərnet",
  "data": "ˈdeɪtə",
  "text": "tɛkst",
  "speech": "spiːtʃ",
  "audio": "ˈɔːdiəʊ",
  "model": "ˈmɒdəl",
  // Prepositions / conjunctions
  "of": "əv",
  "in": "ɪn",
  "to": "tuː",
  "for": "fɔːr",
  "on": "ɒn",
  "with": "wɪð",
  "at": "æt",
  "by": "baɪ",
  "from": "frɒm",
  "or": "ɔːr",
  "as": "æz",
  "up": "ʌp",
  "about": "əˈbaʊt",
  "into": "ˈɪntuː",
  "through": "θruː",
  "during": "ˈdjʊərɪŋ",
  "before": "bɪˈfɔːr",
  "after": "ˈæftər",
  "above": "əˈbʌv",
  "below": "bɪˈloʊ",
  "between": "bɪˈtwiːn",
  "out": "aʊt",
  "off": "ɒf",
  "over": "ˈoʊvər",
  "under": "ˈʌndər",
  "again": "əˈɡɛn",
  "then": "ðɛn",
  "here": "hɪər",
  "there": "ðɛr",
  "when": "wɛn",
  "where": "wɛr",
  "how": "haʊ",
  "however": "haʊˈɛvər",
  "also": "ˈɔːlsoʊ",
  "just": "dʒʌst",
  "because": "bɪˈkɒz",
  "than": "ðæn",
  "so": "soʊ",
  "if": "ɪf",
  "while": "waɪl",
  "although": "ɔːlˈðoʊ",
  "though": "ðoʊ",
  "since": "sɪns",
  "until": "ʌnˈtɪl",
  "unless": "ʌnˈlɛs",
  "whether": "ˈwɛðər",
  "but": "bʌt",
  "and": "ænd",
  "nor": "nɔːr",
  "yet": "jɛt",
  "not": "nɒt",
  "very": "ˈvɛri",
  "too": "tuː",
  "only": "ˈoʊnli",
  "even": "ˈiːvən",
  "never": "ˈnɛvər",
  "always": "ˈɔːlweɪz",
  "often": "ˈɒfən",
  "now": "naʊ",
  "still": "stɪl",
  "already": "ɔːlˈrɛdi",
  "once": "wʌns",
  "first": "fɜːrst",
  "last": "lɑːst",
  "long": "lɒŋ",
  "great": "ɡreɪt",
  "little": "ˈlɪtl",
  "own": "oʊn",
  "same": "seɪm",
  "new": "njuː",
  "old": "oʊld",
  "high": "haɪ",
  "large": "lɑːrdʒ",
  "small": "smɔːl",
  "big": "bɪɡ",
  "next": "nɛkst",
  "early": "ˈɜːrli",
  "young": "jʌŋ",
  "important": "ɪmˈpɔːrtənt",
  "public": "ˈpʌblɪk",
  "private": "ˈpraɪvɪt",
  "real": "riːl",
  "best": "bɛst",
  "free": "friː",
  "true": "truː",
  "false": "fɔːls",
  "good": "ɡʊd",
  "bad": "bæd",
  "sure": "ʃʊr",
  "able": "ˈeɪbl",
  "possible": "ˈpɒsɪbl",
  "late": "leɪt",
  "hard": "hɑːrd",
  "fast": "fɑːst",
  "slow": "sloʊ",
  "dark": "dɑːrk",
  "white": "waɪt",
  "black": "blæk",
  "red": "rɛd",
  "green": "ɡriːn",
  "blue": "bluː",
  "hot": "hɒt",
  "cold": "koʊld",
  "full": "fʊl",
  "short": "ʃɔːrt",
  "easy": "ˈiːzi",
  "clear": "klɪər",
  "deep": "diːp",
  "wide": "waɪd",
  "strong": "strɒŋ",
  "special": "ˈspɛʃəl",
  "different": "ˈdɪfrənt",
  "common": "ˈkɒmən",
  "simple": "ˈsɪmpl",
  "happy": "ˈhæpi",
  "ready": "ˈrɛdi",
  "heavy": "ˈhɛvi",
  "direct": "dɪˈrɛkt",
  "certain": "ˈsɜːrtən",
  "available": "əˈveɪləbl",
  // Numbers as words
  "zero": "ˈzɪəroʊ",
  "one": "wʌn",
  "two": "tuː",
  "three": "θriː",
  "four": "fɔːr",
  "five": "faɪv",
  "six": "sɪks",
  "seven": "ˈsɛvən",
  "eight": "eɪt",
  "nine": "naɪn",
  "ten": "tɛn",
  "eleven": "ɪˈlɛvən",
  "twelve": "twɛlv",
  "thirteen": "ˌθɜːrˈtiːn",
  "fourteen": "ˌfɔːrˈtiːn",
  "fifteen": "ˌfɪfˈtiːn",
  "sixteen": "ˌsɪksˈtiːn",
  "seventeen": "ˌsɛvənˈtiːn",
  "eighteen": "ˌeɪˈtiːn",
  "nineteen": "ˌnaɪnˈtiːn",
  "twenty": "ˈtwɛnti",
  "thirty": "ˈθɜːrti",
  "forty": "ˈfɔːrti",
  "fifty": "ˈfɪfti",
  "sixty": "ˈsɪksti",
  "seventy": "ˈsɛvənti",
  "eighty": "ˈeɪti",
  "ninety": "ˈnaɪnti",
  "hundred": "ˈhʌndrəd",
  "thousand": "ˈθaʊzənd",
  "million": "ˈmɪliən",
  "billion": "ˈbɪliən",
  "half": "hɑːf",
  "quarter": "ˈkwɔːrtər",
  // Contractions
  "i'm": "aɪm",
  "i'll": "aɪl",
  "i've": "aɪv",
  "i'd": "aɪd",
  "you're": "jɔːr",
  "you'll": "juːl",
  "you've": "juːv",
  "you'd": "juːd",
  "he's": "hiːz",
  "he'll": "hiːl",
  "he'd": "hiːd",
  "she's": "ʃiːz",
  "she'll": "ʃiːl",
  "she'd": "ʃiːd",
  "it's": "ɪts",
  "it'll": "ɪtəl",
  "we're": "wɪər",
  "we'll": "wiːl",
  "we've": "wiːv",
  "we'd": "wiːd",
  "they're": "ðɛr",
  "they'll": "ðeɪl",
  "they've": "ðeɪv",
  "they'd": "ðeɪd",
  "that's": "ðæts",
  "there's": "ðɛrz",
  "don't": "doʊnt",
  "doesn't": "ˈdʌzənt",
  "didn't": "ˈdɪdənt",
  "won't": "woʊnt",
  "can't": "kɑːnt",
  "couldn't": "ˈkʊdənt",
  "shouldn't": "ˈʃʊdənt",
  "wouldn't": "ˈwʊdənt",
  "isn't": "ˈɪzənt",
  "aren't": "ɑːrnt",
  "wasn't": "ˈwɒzənt",
  "weren't": "ˈwɜːrənt",
  "haven't": "ˈhævənt",
  "hasn't": "ˈhæzənt",
  "hadn't": "ˈhædənt",
  "let's": "lɛts",
  "what's": "wɒts",
  "who's": "huːz",
  "how's": "haʊz",
  "here's": "hɪərz",
  // Greetings / common phrases
  "hello": "həˈloʊ",
  "hi": "haɪ",
  "hey": "heɪ",
  "bye": "baɪ",
  "goodbye": "ˌɡʊdˈbaɪ",
  "yes": "jɛs",
  "yeah": "jæ",
  "ok": "ˌoʊˈkeɪ",
  "okay": "ˌoʊˈkeɪ",
  "please": "pliːz",
  "thanks": "θæŋks",
  "thank": "θæŋk",
  "sorry": "ˈsɒri",
  "welcome": "ˈwɛlkəm",
  "oh": "oʊ",
  "ah": "ɑː",
  "wow": "waʊ",
};
